name: Docs

on:
  release:
    types:
      - published

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: snok/install-poetry@v1
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'
      - name: Install Dependencies
        run: poetry install --only docs
      - name: Publish Docs
        run: poetry run mkdocs gh-deploy --force
